name: "Terraform deployment"
on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs: 
  terraform: 
    name: "Terraform provision"
    runs-on: ubuntu-latest
    steps:
      #check out the terraform repo code 
      - name: 'Checkout tf source code'
        uses: actions/checkout@v3
      
      # setup terraform cli 
      - name: "TF enginee Setup"
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.3
          terraform_wrapper: false
      - name: "Init tf"
        run: "terraform init"

      - name: "Get tf workspace"
        run: "terraform workspace show"